### PR TITLE
use unordered_map for better performance

### PR DESCRIPTION
**Pull request by svirusxxx**
I tried it on X5650 genproclimit=20
increase from 6100 hps to 6500hps

### CODE REVIEW

**Comment by biblepay** [comment]
Oh my, OK thanks a lot.

I will open the floodgates very soon.  Working on a mining-for-cancer issue now, give me a little bit of time to look at this locally.

**Comment by svirusxxx** [comment]
for x5650 xeon is about 5 to 10 % 
I just searched for better functions to scan, and find many performance sttistics that show it unorderer_map is faster than other hash tables.
example: http://incise.org/hash-table-benchmarks.html

**Comment by svirusxxx** [comment]
and this one: http://scottmeyers.blogspot.de/2015/09/should-you-be-using-something-instead.html

**Comment by biblepay** [comment]
Hmmmm... Not sure if we should induct this, does it appear to be harmless?

**Pull request merged**
